id: skill_task_decompose
name: 任务分解
description: 将复杂任务分解为可执行的小步骤
instructions: |
  1. 理解任务的最终目标
  2. 识别关键里程碑
  3. 将每个里程碑分解为具体步骤
  4. 确定步骤之间的依赖关系
  5. 输出结构化的任务列表
preconditions:
  - has_task_description
effects:
  - has_task_list
methodology_scores:
  meth_simple: 0.9
  meth_iterate: 0.9
parent_methodologies:
  - meth_simple
  - meth_iterate
called_skills: []
